FROM ubuntu:18.04

COPY package.json /taiga-docker/submodule/taiga-front/package.json

# RUN apt update
# RUN apt install -y git curl vim
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

# RUN /bin/bash -c "source ~/.bashrc"

# RUN /bin/bash -c "nvm install v7.7.2"

# RUN /bin/bash -c "npm install -g gulp"

# WORKDIR /taiga-docker/submodule/taiga-front
# RUN /bin/bash -c "npm install"

# CMD ['/bin/bash']