PROJECT_BASE_IN_HOST: ../..
TAIGA:
  HOSTNAME: localhost
  SECRET_KEY: fasdfadsg3qret34542fgvfd
  API_URL: /api/v1/ 
  EVENTS_URL: ws://localhost/events
  HOME: /home/taiga
  
URL_SCHEME: http

BACK_END:
  DEBUG: True
  DB_CHECK_LIMIT_RETRIES: 5
  DB_CHECK_SLEEP_INTERVAL: 5
  PUBLIC_REGISTER_ENABLED: True

FRONT_END:
  DEBUG: 'true'
  PUBLIC_REGISTER_ENABLED: 'true'

POST_GRES_SQL:
  NAME: taiga 
  USER: taiga
  PASSWORD: 123
  HOST: postgresql

# TAIGA_HOSTNAME: 192.168.1.152


# RE_CLONE_SRC_FROM_GIT: False

# HOME_TAIGA: /home/taiga

# BACK_END:
#   CONFIG_HOST: ./backend
#   SRC_HOST: ./backend/src
#   SRC_CONTAINER: /taiga-back
#   DATA_HOST: ./taiga-back
#   PORT: 8000
# API_SERVER: api

# FRONT_END:
#   BASENAME: taiga-front-dist
#   CONFIG_HOST: ./frontend
#   SRC_BASE: ./frontend/src

# EVENTS:
#   BASENAME: taiga-events
#   git-repo: https://github.com/taigaio/taiga-events.git
#   CONFIG_HOST: ./events
#   SRC_BASE: ./events/src
#   PORT: 8888
#   SERVER: events

# POSTGRES:
#   SERVER: pg_db
#   USER: taiga
#   PASSWORD: taiga
#   VOLUMN_PATH: ./db/postgres

# RABBITMQ:
#   SERVER: rabbitmq
#   HOSTNAME: mymq
#   DEFAULT_USER: taiga
#   DEFAULT_PASS: taiga